config/routes.rb
Rails.application.routes.draw do
  # adminログイン
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  # userログインサインアップ
  devise_for :users, :controllers => {
    :registrations => "users/registrations"
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # 管理者関連
  namespace :admin do
    patch 'users/out' => 'users#out'
    resources :posts, only: [:index, :show, :destroy, :update]
    resources :users, only: [:show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
  end

  # user関連
  scope module: :user do
    get 'users/confirm' => 'users#confirm', as: 'confirm'
    patch 'users/out' => 'users#out', as: 'out'
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get :search
      end
    end

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resource :reports, only: [:create]
      collection do
        get :search
      end
    end
    
    resources :notifications, only: [:index]
    get 'dogs/dog_form' => 'dogs#dog_form', as: 'dog_form'
    resources :dogs, only: [:create, :destroy]
  end

  # top関連
  get 'about' => 'homes#about'
  root to: 'homes#top'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :dogs, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reports, dependent: :destroy

  attachment :profile_image

  # user一覧にあるuserが飼っている犬種と大きさを検索する
  def self.search(dog_size, search)
    if search != "" && dog_size != ""
      User.joins(:dogs).where("dogs.dog_size = ? and dogs.dog_type LIKE ?", "#{dog_size}","%#{search}%").distinct
    elsif search != ""
      User.joins(:dogs).where("dogs.dog_type LIKE ?","%#{search}%").distinct
    elsif dog_size != ""
      User.joins(:dogs).where("dogs.dog_size = ? ", "#{dog_size}").distinct
    else
      User.all
    end
  end

  with_options presence: true do
    validates :email, uniqueness: true
    validates :name, length: { maximum: 20 }
  end

  # 自分がフォローされる（被フォロー）
  has_many :reverse_of_relationships,
                                    class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent: :destroy
  # 自分がフォローする（与フォロー）
  has_many :relationships,
                          class_name: "Relationship",
                          foreign_key: "follower_id",
                          dependent: :destroy

  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  # フォロー・フォロワー関連のメソッド
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # ゲストログイン用のメソッド
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  # 退会済みのユーザーが同じアカウントでログイン出来ないように制約、is_deletedがfalseならtrueを返す
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def create_notification_follow!(current_user, visited_id)
    # すでに「フォローされているか」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, visited_id, 'follow'])
    # フォローされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: visited_id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_posts_path, notice: "userの退会情報を更新しました"
    end
  end

  def user_params
    params.require(:user).permit(:is_deleted)
  end
end

app/controllers/user/dogs_controller.rb
class User::DogsController < ApplicationController
  before_action :authenticate_user!

  def dog_form
    @user = current_user
    @dogs = @user.dogs
    @dog = Dog.new
  end
  
  def create
    @dog = Dog.new(dog_params)
    @dog.user_id = current_user.id
    if @dog.save
      redirect_to dog_form_path, notice: "わんちゃんの登録が完了しました"
    else
      @user = current_user
      @dogs = @user.dogs
      render 'dog_form'
    end
  end

  def destroy
    dog = Dog.find(params[:id])
    dog.destroy
    redirect_to request.referer, notice: "わんちゃんの情報を削除しました"
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :dog_type, :dog_size)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = Favorite.new(post_id: @post.id, user_id: current_user.id)
    favorite.save
    @post.create_notification_like!(current_user)
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = Favorite.find_by(post_id: @post.id, user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post_comment = current_user.post_comments.new(post_comment_params)
    @post_comment.post_id = @post.id
    @post_comment.save
    @post = @post_comment.post
    @post.create_notification_post_comment!(current_user, @post_comment.id)
  end

  def destroy
    @post = Post.find(params[:post_id])
    PostComment.find(params[:id]).destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @posts = Post.joins(:user).where(users: { is_deleted: false }).order(created_at: :desc).page(params[:page]).per(12)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: "投稿が完了しました"
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿の編集が完了しました"
    else
      render "edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: "投稿を削除しました"
  end

  def search
    @posts = Post.joins(:user).where(users: { is_deleted: false }).search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(12)
    if params[:category_id].present?
      @posts = @posts.where(category_id: params[:category_id])
    end
    if params[:dog_size].present?
      @posts = @posts.where(dog_size: params[:dog_size])
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :category_id, :place, :address, :introduction, :dog_size,
                                 :latitude, :longitude, :report)
  end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  before_action :authenticate_user!

  # フォロー機能を作成・保存・削除する
  def create
    current_user.follow(params[:user_id])
    @user = current_user
    @user.create_notification_follow!(current_user, params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー・フォロワー一覧を表示する
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/user/reports_controller.rb
class User::ReportsController < ApplicationController
  def create
    report = current_user.reports.new(post_id: params[:post_id])
    if report.save
      redirect_to request.referer, notice: "不適切な表現の投稿を通報しました"
    else
      render show
    end
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where(is_deleted: false).order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @dogs = @user.dogs
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "user情報の更新に成功しました。"
    else
      render :edit
    end
  end

  def search
    @users = User.where(is_deleted: false).search(params[:dog_size], params[:keyword]).order(created_at: :desc).page(params[:page]).per(6)
  end

  def confirm
  end

  # user退会処理
  def out
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :profile_image, :is_deleted)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  protected

  # 会員の論理削除の記述。退会後は、同じアカウントで利用不可
  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "このアカウントは退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/users/confirm.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-7 offset-md-4 offset-lg-4 mt-5 mb-2"><h1>退会お手続き</h1></div>
      </div>
      <div class="col-md-9 offset-md-2 mb-5">
        <p class="confirm text-center my-4">
          退会手続きをされますと、全てのサービスがご利用いただけなくなります。
          再度ご利用をいただく場合には、新規登録のお手続きが必要になります。
          本当に退会してよろしいですか？
        </p>
      </div>  
    
        
        <div class="row my-5">
          <div class="col-md-3 offset-md-4 offset-lg-4 my-5"><%= link_to "退会する", out_path, method: :patch, data: { confirm: "本当に退会しますか？" }, class: "btn btn-danger" %></div>
          <div class="col-md-3 my-5"><%= link_to "退会しない", user_path(current_user), class: "btn btn-primary" %></div>
        </div>  
    </div>
  </div>
</div>

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 mx-auto py-5">
      <h1>User情報編集フォーム</h1>
        <%= render 'layouts/errors', obj: @user %>
        
        <%= form_with model: @user, local:true do |f| %>
          <div class="form-group my-5">
            <h4>画像</h4>
            <%= f.attachment_field :profile_image, class: "form-control-file", size: "100x100", fallback: "no_image.jpg" %>
          </div>
  
          <div class="form-group my-5">
            <h4>名前</h4>
            <%= f.text_field :name, class: "form-control" %>
          </div>
  
          <div class="form-group my-5">
            <h4>email</h4>
            <%= f.email_field :email, class: "form-control" %>
          </div>
  
          <div class="form-group my-5">
            <%= f.submit "更新", class: "btn-edit" %>
          </div>
        <% end %>
       
    </div>  
  </div>
</div>
<div class="row flex-row-reverse py-5">
  <div class="col-md-3 "><%= link_to "退会する", confirm_path, class: "btn btn-delete btn-sm" %></div>
</div>

app/views/user/users/index.html.erb
<div class="row my-3 ">
  <div class="col-lg-4 offset-lg-1">
    <h1>User一覧</h1>
  </div>
  <div class="col-lg-3 offset-lg-4">
    <%= form_with(url: search_users_path,method: :get, local: true, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "userが飼っている犬種を入力", class: "search-input form-control" %>
      <%= form.select :dog_size, Dog.dog_sizes.map {|k, v| [k, v]}, {include_blank: 'sizeすべて'} %>
      <%= form.submit "検索", class: "btn search-btn btn-secondary btn-sm" %>
    <% end %>
  </div>
</div>

<div class="row">
    <div class="col-md-8 offset-1">
      <table class="table table-borderless table-hover">
        <tbody>
          <% @users.each do |user| %>
              <tr>
                <td style="width: 40%">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100", class: "rounded-circle" %>
                  <% end %>
                </td>
                <td style="width: 30%">
                  <%= user.name %>
                </td>
                <td style="width: 30%">
                  投稿数 <%= user.posts.count %>
                </td>
                <td></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
<div class="row">
  <div class="col-2 col-md-4 col-lg-5"></div>
  <div class="col-8 col-md-4 my-3"><%= paginate @users %></div>
</div>

app/views/user/users/search.html.erb
<div class="row">
    <div class="col-md-8 offset-1">
      <table class="table table-borderless table-hover">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td style="width: 40%">
                <%= link_to user_path(user) do %>
                  <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100", class: "rounded-circle" %>
                <% end %>
              </td>
              <td style="width: 30%">
                <%= user.name %>
              </td>
              <td style="width: 300%">
                投稿数 <%= user.posts.count %>
              </td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/user/users/show.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3 col-md-10 col-lg-3 offset-md-1 my-5">
    <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "250x250", class: "rounded-circle" %>
      <% if @user == current_user %>
        <div class="row mt-5">
          <div class="col-md-5 col-lg-5 ml-lg-5 my-4">
            <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-edit"></i>
            <% end %>
          </div>
        </div>
        <div class="row mt-2">
          <div class="col-md-5 col-lg-5 ml-lg-5 mb-4">
            <%= link_to dog_form_path, class: "btn btn-outline-info btn-block" do %>
              <i class="fas fa-paw"></i>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
  <div class="col-sm-6 offset-sm-4 col-md-8 col-lg-6 offset-md-1 my-5 pt-lg-3">
    <div class="row mb-4">
          <div class="col-md-3">名前</div>
          <div class="col-md-3"><%= @user.name %></div>

          <!--userが本人だったら表示する-->
        <% if @user.id == current_user.id %>
          <div class="col-md-3"><%= @user.email %></div>
        <% end %>

        <% if @user != current_user %>
          <% if current_user.following?(@user) %>
              <div class="col-md-3"><%= link_to "フォロー解除", user_relationships_path(user_id: @user.id), method: :delete, class: "btn-create btn-sm" %></div>
          <% else %>
              <div class="col-md-3"><%= link_to "フォローする", user_relationships_path(user_id: @user.id), method: :post, class: "btn-create btn-sm" %></div>
          <% end %>
        <% end %>
    </div>
    <div class="row mb-4">
      <div class="col-md-3">フォロー数</div>
      <div class="col-md-3"><%= link_to @user.followings.count, user_followings_path(user_id: @user.id) %></div>
      <div class="col-md-3">フォロワー数</div>
      <div class="col-md-3"><%= link_to @user.followers.count, user_followers_path(user_id: @user.id) %></div>
    </div>
    <div class="row">
      <% @dogs.each do |dog| %>
        <div class="col-md-3 mb-2">ワンちゃん名</div>
        <div class="col-md-3 mb-2"><%= dog.name %>ちゃん</div>
        <div class="col-md-4 mb-2"><%= dog.dog_type %></div>
        <div class="col-md-2 mb-5"><%= dog.dog_size %></div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1 col-md-1 my-2">
    <h4 class="my-2">投稿一覧</h4>
      <table class="table my-5">
        <thead class="user-post-thead">
          <tr>
            <th></th>
            <th>place</th>
            <th>住所</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @posts.each do |post| %>
          <tbody>
             <tr>
                <td><%= link_to post_path(post) do %>
                      <%= attachment_image_tag post, :image, fallback: "no_image.jpg",  size: "100x100", class: "post-image" %>
                    <% end %>
                </td>
                <td><%= link_to post.place, post_path(post) %></td>
                <td><%= post.address %></td>
                <td></td>
                <td></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>

<div class="row my-3">
  <div class="col-4 col-md-4 col-lg-5"></div>
  <div class="col-4 col-md-4"><%= paginate @posts %></div>
</div>