config/routes.rb
Rails.application.routes.draw do
  # adminログイン
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  # userログインサインアップ
  devise_for :users, :controllers => {
    :registrations => "users/registrations"
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # 管理者関連
  namespace :admin do
    patch 'users/out' => 'users#out'
    resources :posts, only: [:index, :show, :destroy, :update]
    resources :users, only: [:show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
  end

  # user関連
  scope module: :user do
    get 'users/confirm' => 'users#confirm', as: 'confirm'
    patch 'users/out' => 'users#out', as: 'out'
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get :search
      end
    end

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resource :reports, only: [:create]
      collection do
        get :search
      end
    end
    
    resources :notifications, only: [:index]
    get 'dogs/dog_form' => 'dogs#dog_form', as: 'dog_form'
    resources :dogs, only: [:create, :destroy]
  end

  # top関連
  get 'about' => 'homes#about'
  root to: 'homes#top'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to admin_categories_path, notice: "カテゴリーを保存しました"
    else
      @categories = Category.all
      render :index
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(params_category)
      redirect_to admin_categories_path, notice: "カテゴリーを編集しました"
    else
      render :edit
    end
  end

  private

  def params_category
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
  <div class="row my-5">
    <div class="col-md-9 offset-2">
      <div class="col-md-3 offset-3 my-5">
        <%= render 'layouts/errors', obj: @category %>
          <h2>カテゴリー編集</h2>
            <%= form_with model: [:admin, @category], local: true do |f| %>
              <div class="form-group my-5">
                <h4 class="my-5">カテゴリー名</h4>
                  <%= f.text_field :name, class: "form-control my-3" %>
                  <%= f.submit '編集', class: 'btn btn-edit my-3' %>
              </div>  
            <% end %>
      </div>
      <div class="col-md-3"><%= link_to "一覧へ戻る", admin_categories_path, class: "btn btn-sign-in" %></div>
    </div>  
  </div>    

app/views/admin/categories/index.html.erb
<div class="row my-5">
  <div class="col-md-3 offset-1 my-5">
    <%= render 'layouts/errors', obj: @category %>
    <h3>カテゴリー登録</h3>
    <%= form_with model: [:admin, @category], local: true do |f| %>
      <div class="form-group my-5">
        <h4 class="mt-5 mb-4">カテゴリー名</h4>
          <%= f.text_field :name, class: "form-control my-3" %>
          <%= f.submit '新規登録', class: 'btn btn-create my-3' %>
      </div>  
    <% end %>
  </div>
  <div class="col-md-5 offset-1">
    <table class="table">
      <tr>
        <th></th>
        <th>カテゴリー名</th>
        <th></th>
      </tr>
        <% @categories.each do |category| %>
      <tr>
        <td></td>
        <td><%= category.name %></td>
        <td><%= link_to "編集", edit_admin_category_path(category),class: 'btn btn-edit btn-sm' %></td>
      </tr>    
        <% end %>
    </table>    
  </div>
</div>