config/routes.rb
Rails.application.routes.draw do
  # adminログイン
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  # userログインサインアップ
  devise_for :users, :controllers => {
    :registrations => "users/registrations"
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # 管理者関連
  namespace :admin do
    patch 'users/out' => 'users#out'
    resources :posts, only: [:index, :show, :destroy, :update]
    resources :users, only: [:show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
  end

  # user関連
  scope module: :user do
    get 'users/confirm' => 'users#confirm', as: 'confirm'
    patch 'users/out' => 'users#out', as: 'out'
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get :search
      end
    end

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resource :reports, only: [:create]
      collection do
        get :search
      end
    end
    
    resources :notifications, only: [:index]
    get 'dogs/dog_form' => 'dogs#dog_form', as: 'dog_form'
    resources :dogs, only: [:create, :destroy]
  end

  # top関連
  get 'about' => 'homes#about'
  root to: 'homes#top'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # いいね機能の定義、存在していればtrue、存在していなければfalseを返す
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  # 通報ボタンの定義
  def reported_by?(user)
    reports.where(user_id: user.id).empty?
  end

  attachment :image

  enum dog_size: { "小型犬": 0, "中型犬": 1, "大型犬": 2, "超大型犬": 3 }

  # 住所と場所の検索
  def self.search(search)
    if search != ""
      @posts = Post.where("address LIKE? OR place LIKE?", "%#{search}%", "%#{search}%")
    else
      Post.all
    end
  end

  # バリデーション
  with_options presence: true do
    validates :place
    validates :introduction, length: { maximum: 1000 }
    validates :address
    validates :latitude
    validates :longitude
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメント機能のメソッド
  def create_notification_post_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    # report（通報)があったpost(投稿)だけを多い順で並べる
    if params[:order] == 'desc'
      @posts = Post.joins(:reports).group(:post_id).order('count(post_id) desc').page(params[:page]).per(10)
    # report（通報)があったpost(投稿)だけを少ない順で並べる
    elsif params[:order] == 'asc'
      @posts = Post.joins(:reports).group(:post_id).order('count(post_id) asc').page(params[:page]).per(10)
    # すべての投稿を表示  
    else
      @posts = Post.order(created_at: :desc).page(params[:page]).per(10)
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to admin_posts_path, notice: "投稿を削除しました"
    end
  end

  private

  def post_params
    params.require(:post).permit(:report)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_posts_path, notice: "userの退会情報を更新しました"
    end
  end

  def user_params
    params.require(:user).permit(:is_deleted)
  end
end

app/controllers/user/dogs_controller.rb
class User::DogsController < ApplicationController
  before_action :authenticate_user!

  def dog_form
    @user = current_user
    @dogs = @user.dogs
    @dog = Dog.new
  end
  
  def create
    @dog = Dog.new(dog_params)
    @dog.user_id = current_user.id
    if @dog.save
      redirect_to dog_form_path, notice: "わんちゃんの登録が完了しました"
    else
      @user = current_user
      @dogs = @user.dogs
      render 'dog_form'
    end
  end

  def destroy
    dog = Dog.find(params[:id])
    dog.destroy
    redirect_to request.referer, notice: "わんちゃんの情報を削除しました"
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :dog_type, :dog_size)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = Favorite.new(post_id: @post.id, user_id: current_user.id)
    favorite.save
    @post.create_notification_like!(current_user)
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = Favorite.find_by(post_id: @post.id, user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post_comment = current_user.post_comments.new(post_comment_params)
    @post_comment.post_id = @post.id
    @post_comment.save
    @post = @post_comment.post
    @post.create_notification_post_comment!(current_user, @post_comment.id)
  end

  def destroy
    @post = Post.find(params[:post_id])
    PostComment.find(params[:id]).destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @posts = Post.joins(:user).where(users: { is_deleted: false }).order(created_at: :desc).page(params[:page]).per(12)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: "投稿が完了しました"
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿の編集が完了しました"
    else
      render "edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: "投稿を削除しました"
  end

  def search
    @posts = Post.joins(:user).where(users: { is_deleted: false }).search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(12)
    if params[:category_id].present?
      @posts = @posts.where(category_id: params[:category_id])
    end
    if params[:dog_size].present?
      @posts = @posts.where(dog_size: params[:dog_size])
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :category_id, :place, :address, :introduction, :dog_size,
                                 :latitude, :longitude, :report)
  end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  before_action :authenticate_user!

  # フォロー機能を作成・保存・削除する
  def create
    current_user.follow(params[:user_id])
    @user = current_user
    @user.create_notification_follow!(current_user, params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー・フォロワー一覧を表示する
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/user/reports_controller.rb
class User::ReportsController < ApplicationController
  def create
    report = current_user.reports.new(post_id: params[:post_id])
    if report.save
      redirect_to request.referer, notice: "不適切な表現の投稿を通報しました"
    else
      render show
    end
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where(is_deleted: false).order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @dogs = @user.dogs
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "user情報の更新に成功しました。"
    else
      render :edit
    end
  end

  def search
    @users = User.where(is_deleted: false).search(params[:dog_size], params[:keyword]).order(created_at: :desc).page(params[:page]).per(6)
  end

  def confirm
  end

  # user退会処理
  def out
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :profile_image, :is_deleted)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  protected

  # 会員の論理削除の記述。退会後は、同じアカウントで利用不可
  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "このアカウントは退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/user/posts/_post_index.html.erb
  <!--投稿一覧-->
  <% posts.each do |post| %>
      <div class="col-sm-9 offset-sm-2 col-md-3 offset-md-0">
        <div class="card-link my-3">
          <div class="card my-3 mx-2">
            <%= link_to post_path(post), style: "color: black;" do %>
              <%= attachment_image_tag post, :image, fallback: "no_image.jpg", size: "250x250", class: "card-img-top" %>
              <div class="card-body">
                <h5 class="card-title"><%= post.place %></h5>
                <p class="card-text"><%= post.address %></p>
                <p class="card-text"><%= post.introduction %></p>
            <% end %>
                <p class="card-text pt-2"><i class="far fa-comment-dots"></i><%= post.post_comments.count %></p>
                <p class="card-text my-0">
                  <% if user_signed_in? %>
                    <div id="favorite-btn<%= post.id %>">
                      <%= render 'user/favorites/favorite_btn', post: post %>
                    </div>
                  <% end %>
                </p>
                <p class="card-text"><small class="text-muted"><%= post.created_at.strftime('%Y/%m/%d') %></small></p>
              </div>
          </div>
        </div>
      </div>
  <% end %>

app/views/user/posts/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-6 mx-auto py-5">
    <h1 class="my-3">投稿編集フォーム</h1>
      <%= render 'layouts/errors', obj: @post %>
        <%= form_with model: @post, local:true do |f| %>

          <div class="form-group my-3">
            <h4 class="my-3">画像</h4>
            <%= f.attachment_field :image, class: "form-control-file", size: "100x100", fallback: "no_image.jpg" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-3">カテゴリー</h4>
            <%= f.collection_select :category_id, Category.all, :id, :name, class: "form-control" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-3">place名</h4>
            <%= f.text_field :place, class: "form-control" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-3">住所</h4>
            <%= f.text_field :address, class: "form-control" %>
          </div>
          <div class="form-group my-3">
            <%= f.hidden_field :latitude, class: "form-control form-latitude" %>
            <%= f.hidden_field :longitude, class: "form-control form-longitude" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-3">説明</h4>
            <%= f.text_area :introduction, class: "form-control" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-4">利用可能わんちゃんsize</h4>
            <p class="text-danger">※place場所でどのワンちゃんのsizeまで利用可能かを選択してください</p>
            <!--gemのenumを使っていない時の書き方-->
            <%= f.select :dog_size, Post.dog_sizes.keys.map {|k| [k, k]}, {}, { class: 'form-control', style: 'margin-bottom: 15px;', data: {} } %>
          </div>

          <div class="form-group my-5">
            <%= f.submit "投稿編集", class: "btn-edit mt-3" %>
          </div>

        <% end %>

  </div>
</div>

<script>

  function initMap(){
    let geocoder = new google.maps.Geocoder()
    $('.form-address').blur(function () {
      let address = $(this).val();
      geocoder.geocode( { 'address': address }, function(results, status) {
        if (status == 'OK') {
          let location = results[0].geometry.location;
          $('.form-latitude').val(location.lat());
           $('.form-longitude').val(location.lng());
        } else {
          alert('該当する結果がありませんでした：' + status);
        }
      });
      console.log(address)
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['G_KEY'] %>&callback=initMap" async defer></script>

app/views/user/posts/index.html.erb
  <div class="row">
    <div class="col-lg-3 offset-lg-9 mt-3 mb-2">
      <%= form_with(url: search_posts_path,method: :get, local: true, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "住所、place名を入力", class: "search-input form-control" %>
        <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "すべて", required: "required" %>
        <%= form.select :dog_size, Post.dog_sizes.map {|k, v| [k, v]}, {include_blank: '可能なsizeすべて'} %>
        <%= form.submit "検索", class: "btn btn-secondary btn-sm" %>
      <% end %>
    </div>
  </div>

  <div class="row row-cols-1 row-cols-md-4 g-5">
    <%= render 'user/posts/post_index', posts: @posts %>
  </div>

  <div class="row my-3">
    <div class="col-2 col-md-4 col-lg-5"></div>
    <div class="col-8 col-md-4"><%= paginate @posts %></div>
  </div>

app/views/user/posts/new.html.erb
<div class="row my-2">
  <div class="col-sm-12 col-md-8 col-lg-6 mx-auto py-3">
    <h1 class="my-3">新規投稿フォーム</h1>
      <%= render 'layouts/errors', obj: @post %>
        <%= form_with model: @post, local:true do |f| %>

          <div class="form-group my-3">
            <h4 class="my-3">画像</h4>
            <%= f.attachment_field :image, class: "form-control-file", size: "100x100", fallback: "no_image.jpg" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-3">カテゴリー</h4>
            <%= f.collection_select :category_id, Category.all, :id, :name, class: "form-control" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-4">place名</h4>
            <%= f.text_field :place, class: "form-control" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-4">住所</h4>
            <%= f.text_field :address, class: "form-control form-address" %>
          </div>
          <div class="form-group my-3">
            <%= f.hidden_field :latitude, class: "form-control form-latitude" %>
            <%= f.hidden_field :longitude, class: "form-control form-longitude" %>
          </div>
          <div class="form-group my-3">
            <h4 class="my-4">説明</h4>
            <%= f.text_area :introduction, class: "form-control" %>
          </div>

          <div class="form-group my-3">
            <h4 class="my-4">利用可能わんちゃんsize</h4>
            <p class="text-danger">※place場所でどのワンちゃんのsizeまで利用可能かを選択してください</p>
            <!--gemのenum-helpを使っていない時の書き方-->
            <%= f.select :dog_size, Post.dog_sizes.keys.map {|k| [k, k]}, {}, { class: 'form-control', style: 'margin-bottom: 15px;', data: {} } %>
          </div>

          <div class="form-group my-4">
            <%= f.submit "新規投稿", class: "btn-create mt-3" %>
          </div>

        <% end %>
  </div>
</div>

<script>

  function initMap(){
    let geocoder = new google.maps.Geocoder()
    $('.form-address').blur(function () {
      let address = $(this).val();
      geocoder.geocode( { 'address': address }, function(results, status) {
        if (status == 'OK') {
          let location = results[0].geometry.location;
          $('.form-latitude').val(location.lat());
           $('.form-longitude').val(location.lng());
        } else {
          alert('該当する結果がありませんでした：' + status);
        }
      });
      console.log(address)
    });
  }
</script><script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['G_KEY'] %>&callback=initMap" async defer></script>

app/views/user/posts/search.html.erb
<div class="row row-cols-1 row-cols-md-4 g-5">
  <%= render 'user/posts/post_index', posts: @posts %>
</div>

<div class="row">
  <div class="col-5"></div>
  <div class="col-6 mt-3"><%= paginate @posts %></div>
</div>

app/views/user/posts/show.html.erb
<div class="row my-3">
  <div class="col-sm-8 col-md-8 col-lg-5 offset-sm-2 offset-md-2 offset-lg-1 py-5">
    <div class="mb-5 py-5"><%= attachment_image_tag @post, :image, class: "img-fluid rounded align-self-center", fallback: "no_image.jpg", size: "450x450" %></div>
    <div id=map></div>
  </div>

  <div class="col-sm-10 col-md-8 col-lg-5 offset-sm-1 offset-md-2 offset-lg-0 py-5 pt-5">
    <div class="row my-5">
      <div class="col-12">
        <table class="table">
          <tr>
            <td style="width: 30%" >名前</td>
            <td style="width: 70%"><%= link_to @post.user.name, user_path(@user) %></td>
          </tr>
          <tr></tr>
          <tr>
            <td style="width: 30%">大きさ</td>
            <td style="width: 70%"><%= @post.dog_size %>まで利用可能</td>
          </tr>
          <tr>
            <td style="width: 30%">place名</td>
            <td style="width: 70%"><%= @post.place %></td>
          </tr>
          <tr>
            <td style="width: 30%">カテゴリー</td>
            <td style="width: 70%"><%= @post.category.name %></td>
          </tr>
          <tr>
            <td style="width: 30%">住所</td>
            <td style="width: 70%"><%= @post.address %></td>
          </tr>
          <tr>
            <td style="width: 30%">説明</td>
            <td style="width: 70%"><p class="text-break"> <%= @post.introduction %></td>
          </tr>
          <tr>
            <td style="width: 30%">投稿日時</td>
            <td style="width: 70%"><%= @post.created_at.strftime('%Y/%m/%d') %></td>
          </tr>

          <% if @user.id == current_user.id %>
            <tr>
              <td style="width: 40%"><%= link_to "投稿編集", edit_post_path(@post), class: "btn-edit" %></td>
              <td style="width: 60%"><%= link_to "投稿削除", post_path(@post), method: :delete,class: "btn-delete", data: { confirm: "本当に投稿を削除しますか？" } %></td>
            </tr>
          <% end %>
        </table>

        <div id="favorite-btn<%= @post.id %>">
          <%= render 'user/favorites/favorite_btn', post: @post %>
        </div>

        <div class="comment_index">
          <%= render 'user/post_comments/comment_index', post: @post %>
        </div>

        <%= form_with(model:[@post, @post_comment], remote: true) do |f| %>
          <div class="form-group">
              <%= f.text_area :comment, rows:'3',placeholder: "コメントをここに", class: "form-control text_area" %>
          </div>
          <div class="form-group py-3">
            <%= f.submit "コメントする", class: "btn-create btn-sm" %>
          </div>
        <% end %>
        <% if @user.id != current_user.id %>
          <div class="row">
            <div class="col-sm-3 col-md-3 col-lg-4 offset-sm-9 offset-md-9 offset-lg-8 my-5 py-4">
              <% if @post.reported_by?(current_user) %>
                <%= link_to '通報する', post_reports_path(@post), method: :post, class: "btn btn-delete btn-sm", data: { confirm: "不適切な表現の投稿として通報しますか？" } %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
function initMap(){
  let geocoder = new google.maps.Geocoder()
  let map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: -34.397, lng: 150.644},
  zoom: 15
  });
  let address = '<%= @post.address %>';
  geocoder.geocode( { 'address': address }, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });
}
</script><script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['G_KEY'] %>&callback=initMap" async defer></script>